### ISSUE TITLE
Multiple variables

### ISSUE THREAD

**Issue by noerrororbug** [kiegroup/optaplanner-quickstarts#11]
hi, I'm having trouble when i try to write some cases with Multiple Variables . My code as follows.

There are Multiple Variables:

1. timeslot1 , first Running timetable 
2. timeslot2 , second Running timetable 
3. vehicleJobList , vehicle maintenance job(related to history maintenance job time OR The mileage traveled from the last maintenance operation date to the current date )
4. trackLine  the location code in Parking lot 

a vehicle has at most 2 Running timetable ,also 

genuine PlanningEntity
`
@PlanningEntity
@Data
@NoArgsConstructor
public class Vehicle {

    @PlanningId
    public String vehicleName;

    public LocalDate localDate;

    public BigDecimal currentRunKm;

    @PlanningVariable(nullable = true,valueRangeProviderRefs = {"timeslotList"})
    public Timeslot timeslot1;

    @PlanningVariable(nullable = true,valueRangeProviderRefs = {"timeslotList"})
    public Timeslot timeslot2;

    @PlanningListVariable()
    public List<VehicleJob> vehicleJobList = new ArrayList<>();

    @PlanningVariable(nullable = true)
    public TrackLine trackLine;
    

    public Vehicle(String vehicleName) {
        this.vehicleName = vehicleName;
    }
}
`
`
@Data
@NoArgsConstructor
public class Timeslot {
    // arrive time of the last station 
    private LocalTime arriveTime;
   // departure time  from the parking lot 
    private LocalTime departureTime;

    /**
     *  1 Morning rush hour 2 noon rush hour  3 night rush hour  4 morning & night rush hour  5 low peek
     */
    private String runType;

    private Integer runNum;

    private Integer outNum;
}
`
`
@Data
@NoArgsConstructor
public class TrackLine {

    @PlanningId
    private Integer id;

    private String lineName;

    private String cloumnName;

    @Override
    public String toString() {
        return lineName +  cloumnName;
    }

    public TrackLine(Integer id, String lineName, String cloumnName) {
        this.id = id;
        this.lineName = lineName;
        this.cloumnName = cloumnName;
    }
}
`
Shadow Entity
`
@Data
@NoArgsConstructor
@PlanningEntity
public class VehicleJob {

    @PlanningId
    private String id;

    private String jobName;

    private String jobType;

    //private LocalDate localDate;

    private String doType;

    private String vehicleName;

    @InverseRelationShadowVariable(sourceVariableName = "vehicleJobList")
    private Vehicle vehicle;

    @PreviousElementShadowVariable(sourceVariableName = "vehicleJobList")
    protected VehicleJob previousVehicleJob;

    @NextElementShadowVariable(sourceVariableName = "vehicleJobList")
    protected VehicleJob nextVehicleJob;

    @Override
    public String toString() {
        return jobName +  jobType + doType;
    }

    public VehicleJob(String id ,String jobName, String jobType, String doType, String vehicleName) {
        this.id = id;
        this.jobName = jobName;
        this.jobType = jobType;
        this.doType = doType;
        this.vehicleName = vehicleName;
    }

    public VehicleJob(String id ,String jobName, String jobType, String doType) {
        this.id = id;
        this.jobName = jobName;
        this.jobType = jobType;
        this.doType = doType;
    }
}
`
PlanningSolution
`
@Data
@NoArgsConstructor
@PlanningSolution
public class VehicleUseTableSolute {

    @PlanningEntityCollectionProperty
    private List<Vehicle> vehicleList;

    @ValueRangeProvider(id = "timeslotList")
    @ProblemFactCollectionProperty
    private List<Timeslot> timeslotList;

    @ValueRangeProvider
    @ProblemFactCollectionProperty
    private List<TrackLine> trackLineList;

    @PlanningScore
    private HardSoftScore hardSoftScore;

    @ValueRangeProvider
    @ProblemFactCollectionProperty
    private List<VehicleJob> vehicleJobList;

    public VehicleUseTableSolute(List<Vehicle> vehicleList, List<Timeslot> timeslotList, List<TrackLine> trackLineList) {
        this.vehicleList = vehicleList;
        this.timeslotList = timeslotList;
        this.trackLineList = trackLineList;
    }

    public VehicleUseTableSolute(List<Vehicle> vehicleList, List<Timeslot> timeslotList, List<TrackLine> trackLineList, List<VehicleJob> vehicleJobList) {
        this.vehicleList = vehicleList;
        this.timeslotList = timeslotList;
        this.trackLineList = trackLineList;
        this.vehicleJobList = vehicleJobList;
    }
}
`
Solver Config XML

`
    <localSearch>
        <unionMoveSelector>
            <listChangeMoveSelector>
                <valueSelector  variableName="vehicleJobList" />
                <destinationSelector>
                    <valueSelector variableName="vehicleJobList" />
                </destinationSelector>
            </listChangeMoveSelector>
            <listSwapMoveSelector>
                <valueSelector  variableName="vehicleJobList" />
                <secondaryValueSelector variableName="vehicleJobList" />
            </listSwapMoveSelector>
            <cartesianProductMoveSelector>
                <changeMoveSelector>
                    <valueSelector  variableName="timeslot1"/>
                </changeMoveSelector>
                <changeMoveSelector>
                    <valueSelector  variableName="timeslot2"/>
                </changeMoveSelector>
            </cartesianProductMoveSelector>
            <changeMoveSelector>
                <valueSelector  variableName="trackLine"/>
            </changeMoveSelector>
        </unionMoveSelector>
    </localSearch>
`

, i removed constructionHeuristic tag because the the error message

`
Construction Heuristic phase with a list variable does not support moveSelectorConfigList configuration. Remove the moveSelectorConfigList ([CartesianProductMoveSelectorConfig([ChangeMoveSelectorConfig(null, ValueSelectorConfig(timeslot1)), ChangeMoveSelectorConfig(null, ValueSelectorConfig(timeslot2)), ChangeMoveSelectorConfig(null, ValueSelectorConfig(trackLine))])]) from the config.
`

but new error message, 

`
18:44:51.474 [main] INFO org.optaplanner.core.impl.solver.DefaultSolver - Solving started: time spent (81), best score (-4init/0hard/0soft), environment mode (REPRODUCIBLE), move thread count (NONE), random (JDK with seed 0).
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "org.optaplanner.core.impl.domain.variable.index.IndexVariableSupply.getIndex(Object)" is null
	at org.optaplanner.core.impl.heuristic.selector.list.ElementDestinationSelector$1.next(ElementDestinationSelector.java:108)
	at org.optaplanner.core.impl.heuristic.selector.list.ElementDestinationSelector$1.next(ElementDestinationSelector.java:91)
`
i dot know how to init the planListVariable vehicleJobList 
Is there has any use cases and examples for Multiple variables. Thanks.

**Comment by mareknovotny** [comment]
please report this or ask for help in new home at https://github.com/apache/incubator-kie-optaplanner-quickstarts
